### ISSUE TITLE
Unreal Engine 5 Support

### ISSUE THREAD

**Issue by Sagatt** [xtremexp/UT4X-Converter#67]
Is there any plans for it?

**Comment by xtremexp** [comment]
Adding UE1/UE2/UE3 -> UE5 conversion support seems to be possible since UE4 is not that far from UE5 and not that much big changes as concerning file structure, and most important actors (brushes, lights, ...)
For now it's possible to have geometry and light quite easily with converter.
Just convert to UT4 then copy/paste the generate .t3d file in UE5. Prior to that just add a big brush that would fit the converted map.

DmFith from unreal 1 in UE5.1  :
![image](https://user-images.githubusercontent.com/11919600/210092628-de0bb326-5d4c-4ce9-8d70-cb9b81b50e2a.png)

As for UT4->UE5 conversion, no idea yet, need to find a way to extract level structure in ressources (textures, ...) via some command.
I may added a basic conversion support for UE1/2/3 maps in some future at first.

**Comment by Sagatt** [comment]
Well technically Unreal Tournament 4 and UTEditor 4 won't be available anymore in the next few weeks, they're already not available to download anymore, but they'll be deleted.

So having a feature to port the ut99 maps directly to UE5 would be nice to have.

**Comment by xtremexp** [comment]
Not planned for now.  Maybe re-opened in some future when most of remaining current issues or improvements for UE1/2/3/4 will be resolved or completed.
