### ISSUE TITLE
Duke Nukem Forever 2011 Retail Support

### ISSUE THREAD

**Issue by Sagatt** [xtremexp/UT4X-Converter#77]
Well Duke Nukem Forever 2011, the retail version is a complicated topic.

The engine is **Unreal Engine 1**, the **Unreal Tournament retail release version**, which is **basically** the same as the **2001 version** at the core.

And then it has **static meshes** pulled from **Unreal Engine 2**, same with **Karma physics**, the **renderer is completely custom**, and it has **Meqon physics** implemented (basically **early PhysX**).

We have made a custom map editor for the game through reverse engineering, so that allows us to export the maps in .t3d format.
You can download here if you wanna test:
https://www.nexusmods.com/dukenukemforever/mods/3

I'm just wondering if it could be done in the future, since it's still UE1 and now we have basically full 2001 support.

Thanks!

**Comment by xtremexp** [comment]
It's not just "basically" the same as the 2001 version, it's heavily modified engine version.
UT converter uses either ucc.exe or umodel (ueviewer) to extract ressource (textures, staticmeshes, ...)

- ucc.exe is not present (normally in /System folder for 'normal' ue1/ue2 games) and umodel does not support Duke Nukem because as the program maker said it's too modified. (https://www.gildor.org/smf/index.php?topic=893.msg7510#msg7510)

![image](https://user-images.githubusercontent.com/11919600/213932446-2e5c319c-2e4d-4d41-8644-cd3e3dec18de.png)

- Also the textures and staticmeshes are in some unknow usual format packed in some .dat files.

DNF2001 will not be supported.

**Comment by Sagatt** [comment]
We can extract the game models and textures using the software Noesis
https://richwhitehouse.com/index.php?content=inc_projects.php&showproject=91

Here's an article on DNF by Rich Whitehouse
https://richwhitehouse.com/index.php?postid=65

**Comment by Sagatt** [comment]
The DNF2001 ucc.exe works for DNF2011 as far as i'm concerned, could be wrong though

**Comment by vrpixel** [comment]
Would it be possible to at least have a .T3D into UE4 map format containing just placeholder references containing actor name/staticmesh name+location+rotation+scale?

**Comment by xtremexp** [comment]
You can try :
- Convert the .t3d (retrieved opening map from DNF editor - note: i haven't tried) and use UT Converter with this .t3d file 
- Convert the .dnf map file using UT converter but 99.99% sure won't work.
For both case in advanced conversion settings, uncheck 'convert textures/sounds/staticmeshes' and try set DNF2011 folder as UT2004 folder in settings (do not use DNF (2001) it's for Unreal Engine 1)

As said earlier, i do not plan at all to spend time for DNF2011 so good luck with it.

**Comment by vrpixel** [comment]
Unfortunatetly it does not seem to write any files, just creates empty folder.

It's definietly doable, as T3D is just a text format, and one could make a basic parser to make that data paste-able into UE4.
I understand if you have no interest in it.
