### ISSUE TITLE
How would I use this for unreal engine 4 instead of unreal tournament editor?

### ISSUE THREAD

**Issue by HXVRMXN-dev** [xtremexp/UT4X-Converter#84]

**Comment by Thor110** [comment]
> _No description provided._

You just use it as is, convert your selected map and copy the .t3d data into the editor viewport.

Package directory references need updating to match your UE4 file structure.

I wrote a short tutorial on doing this over at moddb but essentially you just need to search the .t3d file for StaticMesh=StaticMesh and Texture= in Notepad++ and update all of the references accordingly.

Along the lines of changing the following
"/Game/Converted/RO-Arad-UT2004/Arad_T_SkyandFog_FogRingColor_Mat.Arad_T_SkyandFog_FogRingColor_Mat"
to match
"/Game/Materials/Arad_T/SkyandFog/FogRingColor_Mat.FogRingColor_Mat"
Removing the excess UT4X converter produces in order to make it work with UE4/5

That is the formula I follow. IE : "/PackageName_CategoryName_" = "/PackageName/CategoryName/" && ".PackageName_CategoryName_" = "."

**Comment by xtremexp** [comment]
Ty for giving answer to the original question guy.
